### ISSUE TITLE
Error when install hyper-sync-settings plugin in Hyper 3.0.2

### ISSUE THREAD

**Issue by yzenati** [dfrankland/hyper-sync-settings#47]
Hello,

I am trying to install the plugin but get an error just after installed.

ProductName:	Mac OS X
ProductVersion:	10.14.6

I installed Hyper from homebrew cask
$ hyper version
3.0.2
$ hyper list
hyper-quit
hyper-sync-settings

<img width="423" alt="Screen Shot 2019-09-19 at 19 23 26" src="https://user-images.githubusercontent.com/9922120/65266259-fc484600-db12-11e9-995a-19956e55fefe.png">

After installing hyper-sync-settings I get this error : 
<img width="339" alt="Screen Shot 2019-09-19 at 19 11 02" src="https://user-images.githubusercontent.com/9922120/65265998-762bff80-db12-11e9-8691-c7022ef24bc6.png">

Note that I get this error right after installing the plugin. If fot exemple I just install hyper-quit it works well.

I don't have a custom .hyper.js config file for the moment, just the basic one.

Thank you

**Comment by dfrankland** [comment]
I just pushed out an update that should fix this. Relevant commit: 7e5b9dec05ded1a971d906029364178a90adb346

**Comment by yzenati** [comment]
Thanks !

It did fix one of the warning but the main problem remains as you can see.

<img width="344" alt="Screen Shot 2019-09-19 at 22 06 26" src="https://user-images.githubusercontent.com/9922120/65282789-16475000-db36-11e9-8ce1-e4729d70197d.png">

I am new in JS but it seems like the problem comes from the way of calling dugite script, isn't ?

<img width="334" alt="Screen Shot 2019-09-19 at 23 45 34" src="https://user-images.githubusercontent.com/9922120/65283620-c4072e80-db37-11e9-9108-0fb8539eaacf.png">

**Comment by dfrankland** [comment]
I had this issue before too, but it went away. Can you try to clear caches and re-install your plugins?

1. Delete all plugins installed
  ```bash
  rm -rf \
    ~/.hyper_plugins/package.json \
    ~/.hyper_plugins/node_modules \
    ~/.hyper_plugins/cache
  ```

2. Click on the `Plugins > Update` menu item to re-install all plugins. Make sure to give it a few seconds to re-install.

3. Exit and re-open Hyper.

**Comment by yzenati** [comment]
Unfortunately it didn't help.

**Comment by angelcustodio** [comment]
Same error of `Git could not be found` in my case.
Any solution for this?

![Screenshot 2019-11-22 at 19 01 26](https://user-images.githubusercontent.com/696902/69449156-818de800-0d5a-11ea-911b-3c99a5693541.png)

**Comment by dfrankland** [comment]
I think that #59 should fix the issue of git not being found. Would y'all be up for trying to upgrade your plugins?

**Comment by yzenati** [comment]
Hello, thanks for you help but the error is still here.
<img width="337" alt="Screen Shot 2019-11-27 at 18 13 19" src="https://user-images.githubusercontent.com/9922120/69745156-fa69b700-1141-11ea-9eab-45209703c77a.png">

**Comment by dfrankland** [comment]
You might need to reinstall all plugins... If you don't mind could you try deleting `~/.hyper_plugins/cache` and `~/.hyper_plugins/node_modules`, then trying to update plugins? After doing so, you'll likely need to quit Hyper and re-open it.

**Comment by stiofand** [comment]
I have the same issue git not found and warning of Buffer, no solutions here fix it, it appears dugite is the offendig library, even with all updates.

**Comment by adamgajzlerowicz** [comment]
I have the same issue on ubuntu. Using AppImage gives more error info:

```
❯ ./hyper-3.0.2-x86_64.AppImage                                                                                                                                      (gke_petpit_europe-north1-a_petpit/default)
Plugin hyper-sync-settings (3.1.0) loaded.
plugins have changed / not init, scheduling plugins installation
Disabling Chromium GPU blacklist
running in prod mode
electron will open file:///tmp/.mount_hyper-P6O6cW/resources/app.asar/index.html
Setting Hyper as default client for ssh:// protocol
hyper-sync-settings error 🔥
no config file found in `/home/adam/.hyper_plugins/.hyper-sync-settings.json`, creating one
hyper-sync-settings error 🔥
could not check in `/home/adam/.hyper_plugins/.hyper-sync-settings.json` for config file
hyper-sync-settings error 🔥
Settings not found! Click for more info.
https://github.com/dfrankland/hyper-sync-settings#setup
Checking for notification messages
Launching yarn: /tmp/.mount_hyper-P6O6cW/hyper /tmp/.mount_hyper-P6O6cW/resources/bin/yarn-standalone.js install --no-emoji --no-lockfile --cache-folder /home/adam/.hyper_plugins/cache
No matching notification messages
[Notification] Error updating plugins.: (node:17514) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
error /home/adam/.hyper_plugins/node_modules/core-js: Command failed.
Exit code: 127
Command: node -e "try{require('./postinstall')}catch(e){}"
Arguments: 
Directory: /home/adam/.hyper_plugins/node_modules/core-js
Output:
/bin/sh: 1: node: not found

(node:17514) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
error /home/adam/.hyper_plugins/node_modules/core-js: Command failed.
Exit code: 127
Command: node -e "try{require('./postinstall')}catch(e){}"
Arguments: 
Directory: /home/adam/.hyper_plugins/node_modules/core-js
Output:
/bin/sh: 1: node: not found
```

I have blank config (removed it all) and after `hyper-sync-settings` and restarting hyper error shows.

It worked perfectly on osx. Ubuntu seems to be having this issue only.

Thanks

**Comment by adamgajzlerowicz** [comment]
For me it is working on osx, but not on ubuntu. I also believe that `dugite` is causing the error

```
hyper-sync-settings error 🔥 Git could not be found at the expected path: '/home/adam/.hyper_plugins/node_modules/dugite/git/bin/git'. This might be a problem with how the application is packaged, so confirm this folder hasn't been removed when packaging.
hyper-sync-settings error 🔥
Git could not be found at the expected path: '/home/adam/.hyper_plugins/node_modules/dugite/git/bin/git'. This might be a problem with how the application is packaged, so confirm this folder hasn't been removed when packaging.
(node:15089) UnhandledPromiseRejectionWarning: Error: Git could not be found at the expected path: '/home/adam/.hyper_plugins/node_modules/dugite/git/bin/git'. This might be a problem with how the application is packaged, so confirm this folder hasn't been removed when packaging.
    at /home/adam/.hyper_plugins/node_modules/dugite/build/lib/git-process.js:87:39
    at exithandler (child_process.js:310:5)
    at ChildProcess.errorhandler (child_process.js:322:5)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:15089) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```
I put symlinked git to that directory, but it started throwing other errors.

As a workaround I downgraded hyper-sync-settings:

`~/.hyper_plugins && npm i --save hyper-sync-settings@3.0.0` 

and I was able to pull my settings.

**Comment by shavidzet** [comment]
> For me it is working on osx, but not on ubuntu. I also believe that `dugite` is causing the error
> 
> ```
> hyper-sync-settings error 🔥 Git could not be found at the expected path: '/home/adam/.hyper_plugins/node_modules/dugite/git/bin/git'. This might be a problem with how the application is packaged, so confirm this folder hasn't been removed when packaging.
> hyper-sync-settings error 🔥
> Git could not be found at the expected path: '/home/adam/.hyper_plugins/node_modules/dugite/git/bin/git'. This might be a problem with how the application is packaged, so confirm this folder hasn't been removed when packaging.
> (node:15089) UnhandledPromiseRejectionWarning: Error: Git could not be found at the expected path: '/home/adam/.hyper_plugins/node_modules/dugite/git/bin/git'. This might be a problem with how the application is packaged, so confirm this folder hasn't been removed when packaging.
>     at /home/adam/.hyper_plugins/node_modules/dugite/build/lib/git-process.js:87:39
>     at exithandler (child_process.js:310:5)
>     at ChildProcess.errorhandler (child_process.js:322:5)
>     at ChildProcess.emit (events.js:182:13)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
>     at onErrorNT (internal/child_process.js:406:16)
>     at process._tickCallback (internal/process/next_tick.js:63:19)
> (node:15089) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> ```
> 
> I put symlinked git to that directory, but it started throwing other errors.
> 
> As a workaround I downgraded hyper-sync-settings:
> 
> `~/.hyper_plugins && npm i --save hyper-sync-settings@3.0.0`
> 
> and I was able to pull my settings.

Thanks
Version downgrade works fine: `~/.hyper_plugins && npm i --save hyper-sync-settings@3.0.0`

**Update:**

It showed up success message, but didn't upload local settings to git :( still find solution
